//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuari
    {   

        public usuari()
        {

        }
        public usuari(string name, string pass, bool type)
        {
            this.name = name;
            this.password = pass;
            this.userType = type;
        }

        public string name { get; set; }
        public string password { get; set; }
        public Nullable<bool> userType { get; set; }
    }
}
